### ISSUE TITLE
Thrice loaded sass.worker.js in TodoList Demo App

### ISSUE THREAD

**Issue by dustin-H** [Wildhoney/Maple.js#10]
Hi,
I just had a look on your demo-app and wondered why it is loading the sass.worker.js file 3 times with the initial load:

![screen shot 2015-05-29 at 16 08 51](https://cloud.githubusercontent.com/assets/6003519/7884370/90af96ba-061d-11e5-871a-27fc93b6b954.png)

Is there any reason why you are doing this, or is this a bug? The file is with 2,6 Mb very big, so I may not want to load this with my smartphone over mobile network ;-)

**Comment by Wildhoney** [comment]
@dustin-H Good spot! All fixed and released as `v1.4.1` :bug:
